# Generated by Django 5.0.4 on 2024-08-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_details', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
