# Generated by Django 5.0.4 on 2024-08-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botengine', '0002_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created']},
        ),
    ]
