# Generated by Django 5.0.4 on 2024-08-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botengine', '0003_alter_log_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='successful_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='successful_logins',
            field=models.IntegerField(default=0),
        ),
    ]
