# Generated by Django 5.0.4 on 2024-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botengine', '0004_bot_successful_bookings_bot_successful_logins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=33)),
            ],
        ),
    ]
