# Generated by Django 5.0.7 on 2024-09-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botengine', '0005_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_key', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
